import CoreLocation
import Foundation
import os

/// The real shape of the Swedish rail network, bundled offline from Trafikverket's National
/// Railway Database (NJDB, CC0), so routes can be drawn following actual track geometry instead
/// of straight lines between stations. Junctions are graph nodes; the long straight-ish runs
/// between them are collapsed into single edges carrying their simplified shape, so the whole
/// network is ~7k nodes/9k edges instead of ~400k raw survey points. See `docs/rail-network.md`
/// for how `RailNetwork.json` is generated from the NJDB GeoPackage.
///
/// Owns loading and caching; the graph data structure and Dijkstra search themselves live in
/// `RailGraph`, which is tested directly against a small synthetic graph (`RailGraphTests`)
/// rather than through this bundle-loading, actor-isolated wrapper.
///
/// Parsing the bundled JSON is done off the main actor and kicked off eagerly at launch (see
/// `AppDependencies`), not lazily on first use, so it isn't competing for the main thread on the
/// exact frame a user taps a train. `route(from:to:)` simply returns `nil` (straight-line
/// fallback) until loading finishes.
@MainActor
@Observable
final class RailNetwork {
    private(set) var isLoaded = false
    private var graph: RailGraph?
    /// Consecutive stop pairs repeat heavily across different trains sharing the same line, so a
    /// warm cache makes re-selecting an already-seen pair instant.
    private var routeCache: [String: [CLLocationCoordinate2D]?] = [:]
    private var loadTask: Task<Void, Never>?
    private let logger = Logger(subsystem: "se.tagkollen.app", category: "RailNetwork")

    static let shared = RailNetwork()

    private init() {}

    /// Kicks off parsing the bundled network on a background task. Call once, early (see
    /// `AppDependencies`) — safe to call more than once: only the first call starts a load, later
    /// ones are no-ops whether it's still in flight, finished, or failed.
    func preload() {
        guard loadTask == nil else { return }
        loadTask = Task { [weak self] in
            await self?.load()
        }
    }

    /// Where the network puts a station on the track (see `RailGraph.stationCoordinate`); `nil`
    /// until loaded or for a station it doesn't cover.
    func stationCoordinate(_ signature: String) -> CLLocationCoordinate2D? {
        graph?.stationCoordinate(signature)
    }

    /// The real-track path between two adjacent stops, or `nil` if either station isn't in the
    /// network (e.g. a foreign border station), the network hasn't finished loading yet, or no
    /// path exists — callers fall back to a straight line in that case.
    func route(from: String, to: String) -> [CLLocationCoordinate2D]? {
        guard let graph else { return nil }
        let key = "\(from)|\(to)"
        if let cached = routeCache[key] {
            return cached
        }
        let path = graph.route(from: from, to: to)
        if routeCache.count >= Self.maxCachedRoutes {
            // Bounded by the pairs a user actually looks at, so this is rarely reached; it just
            // keeps a long-lived session from holding every polyline it ever drew.
            routeCache.removeAll(keepingCapacity: true)
        }
        routeCache[key] = .some(path)
        return path
    }

    private static let maxCachedRoutes = 2000

    // MARK: Loading

    private func load() async {
        guard let url = Bundle.main.url(forResource: "RailNetwork", withExtension: "json") else {
            logger.error("RailNetwork.json not found in bundle")
            return
        }
        do {
            let parsed = try await Task.detached(priority: .utility) {
                try Self.parse(data: Data(contentsOf: url))
            }.value
            graph = parsed
            isLoaded = true
            let nodeCount = parsed.nodeCoordinates.count
            let edgeCount = parsed.edges.count
            let stationCount = parsed.stationNode.count
            logger.debug("Loaded rail network: \(nodeCount) nodes, \(edgeCount) edges, \(stationCount) stations")
        } catch {
            // `String(describing:)`, not `localizedDescription`: the latter hides which index or
            // station a `RailNetworkError`/`DecodingError` is actually complaining about.
            logger.error("Failed to load RailNetwork.json: \(String(describing: error), privacy: .public)")
        }
    }

    /// Pure parsing, off the main actor: JSON decode plus building the adjacency list. Edge
    /// lengths come straight from the bundle (computed once, offline, in export_network.py) — no
    /// per-edge CLLocation distance calculations here.
    ///
    /// The bundle is regenerated by hand from a fresh NJDB drop now and then, so every index it
    /// contains is checked rather than trusted: a malformed file must surface as a thrown error
    /// (logged, straight-line fallback) and not as an out-of-bounds trap on every launch.
    nonisolated static func parse(data: Data) throws -> RailGraph {
        let raw = try JSONDecoder().decode(RawNetwork.self, from: data)
        let nodes = try raw.nodes.map(Self.coordinate)

        var edges: [RailGraph.Edge] = []
        edges.reserveCapacity(raw.edges.count)
        var adjacency = Array(repeating: [RailGraph.Adjacency](), count: nodes.count)
        for rawEdge in raw.edges {
            guard nodes.indices.contains(rawEdge.a), nodes.indices.contains(rawEdge.b) else {
                throw RailNetworkError.invalidBundle("edge \(edges.count) references a node outside 0..<\(nodes.count)")
            }
            guard rawEdge.length > 0 else {
                throw RailNetworkError.invalidBundle("edge \(edges.count) has a non-positive length")
            }
            var points = [nodes[rawEdge.a]]
            try points.append(contentsOf: rawEdge.interior.map(Self.coordinate))
            points.append(nodes[rawEdge.b])
            let edgeIndex = edges.count
            edges.append(RailGraph.Edge(points: points, length: rawEdge.length))
            adjacency[rawEdge.a].append(RailGraph.Adjacency(to: rawEdge.b, edgeIndex: edgeIndex, forward: true))
            adjacency[rawEdge.b].append(RailGraph.Adjacency(to: rawEdge.a, edgeIndex: edgeIndex, forward: false))
        }
        for (signature, node) in raw.stations where !nodes.indices.contains(node) {
            throw RailNetworkError.invalidBundle("station \(signature) references a node outside 0..<\(nodes.count)")
        }
        return RailGraph(nodeCoordinates: nodes, edges: edges, adjacency: adjacency, stationNode: raw.stations)
    }

    private nonisolated static func coordinate(_ pair: [Double]) throws -> CLLocationCoordinate2D {
        guard pair.count == 2 else {
            throw RailNetworkError.invalidBundle("expected a [lat, lon] pair, got \(pair.count) values")
        }
        return CLLocationCoordinate2D(latitude: pair[0], longitude: pair[1])
    }
}

enum RailNetworkError: Error {
    case invalidBundle(String)
}

private struct RawNetwork: Decodable {
    let nodes: [[Double]]
    let edges: [RawEdge]
    let stations: [String: Int]
}

private struct RawEdge: Decodable {
    let a: Int
    let b: Int
    let interior: [[Double]]
    let length: Double

    init(from decoder: any Decoder) throws {
        var container = try decoder.unkeyedContainer()
        a = try container.decode(Int.self)
        b = try container.decode(Int.self)
        interior = try container.decode([[Double]].self)
        length = try container.decode(Double.self)
    }
}
