name: Feature request
description: Suggest an improvement
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like Tågkollen to do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why is this useful?
