#!/usr/bin/env bash
# Prepares a local development environment:
#  1. Creates Config/Secrets.xcconfig from .env.local (TRV_API_KEY=...) if present
#  2. Generates Tagkollen.xcodeproj with XcodeGen
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env.local ]; then
  # shellcheck disable=SC1091
  set -a; source .env.local; set +a
fi

mkdir -p Config
{
  echo "// Generated by Scripts/bootstrap.sh — do not commit."
  echo "TRV_API_KEY = ${TRV_API_KEY:-}"
  echo "DEVELOPMENT_TEAM = ${DEVELOPMENT_TEAM:-}"
} > Config/Secrets.xcconfig

if ! command -v xcodegen >/dev/null 2>&1; then
  echo "xcodegen not found. Install with: brew install xcodegen" >&2
  exit 1
fi
xcodegen generate --quiet
echo "Generated Tagkollen.xcodeproj. Open it with: open Tagkollen.xcodeproj"
